import type { Project } from "@shared/types";

export const mockProjects: Project[] = [
  {
    id: "shigoto-no-mori",
    name: "shigoto-no-mori",
    path: "~/Harp/Software/app/shigoto-no-mori",
    worktrees: [
      {
        id: "shigoto/main",
        projectId: "shigoto-no-mori",
        branch: "main",
        path: "~/Harp/Software/app/shigoto-no-mori",
        status: "clean",
        ahead: 0,
        behind: 0,
        dirtyCount: 0,
        lastCommit: {
          hash: "4a2f236",
          subject: "Scaffold foundation",
          author: "sylophi",
          date: "2026-05-12T12:00:00Z",
        },
        isPrimary: true,
      },
      {
        id: "shigoto/feat-sidebar",
        projectId: "shigoto-no-mori",
        branch: "feat/sidebar",
        path: "~/.shigoto/worktrees/shigoto-no-mori/feat-sidebar",
        status: "ahead",
        ahead: 4,
        behind: 0,
        dirtyCount: 0,
        lastCommit: {
          hash: "9c11ba2",
          subject: "Add project group component",
          author: "sylophi",
          date: "2026-05-12T14:30:00Z",
        },
      },
      {
        id: "shigoto/fix-shell-quote",
        projectId: "shigoto-no-mori",
        branch: "fix/shell-quote",
        path: "~/.shigoto/worktrees/shigoto-no-mori/fix-shell-quote",
        status: "dirty",
        ahead: 1,
        behind: 0,
        dirtyCount: 3,
        lastCommit: {
          hash: "ab21fde",
          subject: "Escape paths with spaces",
          author: "sylophi",
          date: "2026-05-11T19:12:00Z",
        },
      },
    ],
  },
  {
    id: "tuneloupe",
    name: "tuneloupe",
    path: "~/Harp/Software/web/tuneloupe",
    worktrees: [
      {
        id: "tuneloupe/main",
        projectId: "tuneloupe",
        branch: "main",
        path: "~/Harp/Software/web/tuneloupe",
        status: "clean",
        ahead: 0,
        behind: 0,
        dirtyCount: 0,
        lastCommit: {
          hash: "f17a803",
          subject: "Tighten waveform rendering",
          author: "sylophi",
          date: "2026-05-12T09:00:00Z",
        },
        isPrimary: true,
      },
      {
        id: "tuneloupe/feat-eq",
        projectId: "tuneloupe",
        branch: "feat/eq",
        path: "~/.shigoto/worktrees/tuneloupe/feat-eq",
        status: "diverged",
        ahead: 2,
        behind: 1,
        dirtyCount: 7,
        lastCommit: {
          hash: "c0a3217",
          subject: "Stub three-band EQ ladder",
          author: "sylophi",
          date: "2026-05-10T22:14:00Z",
        },
      },
    ],
  },
  {
    id: "fileatlas",
    name: "fileatlas",
    path: "~/Harp/Software/web/fileatlas",
    worktrees: [
      {
        id: "fileatlas/main",
        projectId: "fileatlas",
        branch: "main",
        path: "~/Harp/Software/web/fileatlas",
        status: "clean",
        ahead: 0,
        behind: 0,
        dirtyCount: 0,
        lastCommit: {
          hash: "e44c19b",
          subject: "Switch to TanStack Router",
          author: "sylophi",
          date: "2026-05-09T11:43:00Z",
        },
        isPrimary: true,
      },
    ],
  },
];
