// What the command switch ("Allow control from other devices") hands to
// the account's other devices: each line the switch's panel shows, and
// the calls it covers. A remote gated call names its line in its Grant
// annotation (contract.ts), next to its other annotations, and the
// socket-host proof holds this table to those annotations both ways, so
// the table is the one place to read what the switch gives away.
export const GRANTS = {
  runCommands: {
    title: "Run commands as you",
    detail: "Edit and run scripts, and open and type into terminals.",
    calls: [
      "packageScripts:run",
      "scripts:attach",
      "scripts:cancel",
      "scripts:resize",
      "scripts:run",
      "scripts:write",
      "shigomori:write",
      "terminals:attach",
      "terminals:close",
      "terminals:list",
      "terminals:open",
      "terminals:resize",
      "terminals:write",
    ],
  },
  changeCode: {
    title: "Change your code",
    detail:
      "Create, delete and move worktrees, commit, discard changes, push (force push too), publish new repositories and merge pull requests with this machine's Git and GitHub credentials.",
    calls: [
      "branches:create",
      "branches:delete",
      "branches:rename",
      "git:refreshProject",
      "githubCli:disablePullRequestAutoMerge",
      "githubCli:mergePullRequest",
      "githubCli:publish",
      "githubCli:resolvePullRequestCheckout",
      "githubCli:setPullRequestDraft",
      "mirror:applyGitState",
      "mirror:pause",
      "mirror:release",
      "mirror:resume",
      "mirror:setIgnores",
      "mirror:startTo",
      "mirror:stop",
      "sync:cancelMove",
      "sync:receiveBundle",
      "sync:receiveWorktree",
      "worktreeData:describe",
      "worktrees:abortOperation",
      "worktrees:applyStash",
      "worktrees:checkoutBranch",
      "worktrees:cherryPick",
      "worktrees:commit",
      "worktrees:continueOperation",
      "worktrees:convertExternal",
      "worktrees:create",
      "worktrees:delete",
      "worktrees:deleteStack",
      "worktrees:discardChanges",
      "worktrees:discardHunks",
      "worktrees:dropStash",
      "worktrees:idleAgents",
      "worktrees:mergeBranch",
      "worktrees:mergePrimary",
      "worktrees:mergeUpstream",
      "worktrees:overwrite",
      "worktrees:publish",
      "worktrees:pull",
      "worktrees:pullAndPush",
      "worktrees:push",
      "worktrees:pushForce",
      "worktrees:relocate",
      "worktrees:rename",
      "worktrees:renameBranch",
      "worktrees:resetSoft",
      "worktrees:resolveConflict",
      "worktrees:restoreDiscard",
      "worktrees:restoreStash",
      "worktrees:revertCommit",
      "worktrees:rewordCommit",
      "worktrees:setAutoPull",
      "worktrees:setShelved",
      "worktrees:squashCommit",
      "worktrees:stashChanges",
      "worktrees:switchToPrimaryAndDeleteBranch",
      "worktrees:syncWithPrimary",
      "worktrees:unbindAgent",
    ],
  },
  browseFiles: {
    title: "Browse your files",
    detail:
      "List folders anywhere on this machine, read any file in its worktrees, and add, clone or create projects in it.",
    calls: [
      "fs:isGitRepo",
      "fs:listDirectory",
      "fs:scanForGitRepos",
      "mirror:gitState",
      "mirror:openStream",
      "projects:add",
      "projects:clone",
      "projects:create",
      "runtime:info",
      "sync:hasCommits",
      "sync:ignoredPaths",
      "sync:openSource",
      "sync:worktreeFolder",
      "worktrees:readFile",
    ],
  },
  reachServers: {
    title: "Reach local servers",
    detail: "Forward ports to anything listening on this machine's localhost.",
    calls: ["forward:open"],
  },
  changeApp: {
    title: "Change the app",
    detail:
      "Edit settings, install the CLI, shell hooks and agent hooks, run health check repairs, install updates and move the data folder.",
    calls: [
      "agents:setHooks",
      "agents:status",
      "cli:doctor",
      "cli:doctorFix",
      "cli:install",
      "cli:shellInstall",
      "cli:shellStatus",
      "cli:shellUninstall",
      "cli:status",
      "cli:uninstall",
      "globalConfig:writeDeviceSettings",
      "packageScripts:setLaunchRow",
      "packageScripts:setOrder",
      "packageScripts:setSort",
      "projects:relocate",
      "projects:remove",
      "projects:reorder",
      "runtime:moveDataDir",
      "sharedSettings:merge",
      "updater:check",
      "updater:install",
      "updater:update",
      "worktreeData:write",
    ],
  },
} as const;

export type GrantId = keyof typeof GRANTS;
