import { branchesContract } from "@shared/ipc/modules/branches";
import { clientConfigContract } from "@shared/ipc/modules/clientConfig";
import { dialogContract } from "@shared/ipc/modules/dialog";
import { fsContract } from "@shared/ipc/modules/fs";
import { gitContract } from "@shared/ipc/modules/git";
import { githubCliContract } from "@shared/ipc/modules/githubCli";
import { globalConfigContract } from "@shared/ipc/modules/globalConfig";
import { hygieneContract } from "@shared/ipc/modules/hygiene";
import { launchersContract } from "@shared/ipc/modules/launchers";
import { menuContract } from "@shared/ipc/modules/menu";
import { packageScriptsContract } from "@shared/ipc/modules/packageScripts";
import { portPoolContract } from "@shared/ipc/modules/portPool";
import { projectsContract } from "@shared/ipc/modules/projects";
import { runtimeContract } from "@shared/ipc/modules/runtime";
import { scriptsContract } from "@shared/ipc/modules/scripts";
import { cliContract } from "@shared/ipc/modules/cli";
import { shellContract } from "@shared/ipc/modules/shell";
import { shigomoriContract } from "@shared/ipc/modules/shigomori";
import { updaterContract } from "@shared/ipc/modules/updater";
import { windowContract } from "@shared/ipc/modules/window";
import { worktreesContract } from "@shared/ipc/modules/worktrees";
import { branchesHandlers } from "./modules/branches";
import { clientConfigHandlers } from "./modules/clientConfig";
import { dialogHandlers } from "./modules/dialog";
import { fsHandlers } from "./modules/fs";
import { gitHandlers } from "./modules/git";
import { githubCliHandlers } from "./modules/githubCli";
import { globalConfigHandlers } from "./modules/globalConfig";
import { hygieneHandlers } from "./modules/hygiene";
import { launchersHandlers } from "./modules/launchers";
import { menuHandlers } from "./modules/menu";
import { packageScriptsHandlers } from "./modules/packageScripts";
import { portPoolHandlers } from "./modules/portPool";
import { projectsHandlers } from "./modules/projects";
import { runtimeHandlers } from "./modules/runtime";
import { scriptsHandlers } from "./modules/scripts";
import { cliHandlers } from "./modules/cli";
import { shellHandlers } from "./modules/shell";
import { shigomoriHandlers } from "./modules/shigomori";
import { updaterHandlers } from "./modules/updater";
import { windowHandlers } from "./modules/window";
import { worktreesHandlers } from "./modules/worktrees";
import { registerContract } from "./register";

export function registerIpcHandlers(): void {
  registerContract(clientConfigContract, clientConfigHandlers);
  registerContract(windowContract, windowHandlers);
  registerContract(projectsContract, projectsHandlers);
  registerContract(dialogContract, dialogHandlers);
  registerContract(runtimeContract, runtimeHandlers);
  registerContract(shellContract, shellHandlers);
  registerContract(branchesContract, branchesHandlers);
  registerContract(globalConfigContract, globalConfigHandlers);
  registerContract(portPoolContract, portPoolHandlers);
  registerContract(menuContract, menuHandlers);
  registerContract(launchersContract, launchersHandlers);
  registerContract(packageScriptsContract, packageScriptsHandlers);
  registerContract(fsContract, fsHandlers);
  registerContract(gitContract, gitHandlers);
  registerContract(githubCliContract, githubCliHandlers);
  registerContract(worktreesContract, worktreesHandlers);
  registerContract(hygieneContract, hygieneHandlers);
  registerContract(scriptsContract, scriptsHandlers);
  registerContract(cliContract, cliHandlers);
  registerContract(shigomoriContract, shigomoriHandlers);
  registerContract(updaterContract, updaterHandlers);
}
