import { branchesContract } from "@shared/ipc/modules/branches/contract";
import { dialogContract } from "@shared/ipc/modules/dialog/contract";
import { fsContract } from "@shared/ipc/modules/fs/contract";
import { githubCliContract } from "@shared/ipc/modules/githubCli/contract";
import { globalConfigContract } from "@shared/ipc/modules/globalConfig/contract";
import { launchersContract } from "@shared/ipc/modules/launchers/contract";
import { menuContract } from "@shared/ipc/modules/menu/contract";
import { packageScriptsContract } from "@shared/ipc/modules/packageScripts/contract";
import { portPoolContract } from "@shared/ipc/modules/portPool/contract";
import { projectsContract } from "@shared/ipc/modules/projects/contract";
import { runtimeContract } from "@shared/ipc/modules/runtime/contract";
import { scriptsContract } from "@shared/ipc/modules/scripts/contract";
import { shellContract } from "@shared/ipc/modules/shell/contract";
import { shigomoriContract } from "@shared/ipc/modules/shigomori/contract";
import { updaterContract } from "@shared/ipc/modules/updater/contract";
import { worktreesContract } from "@shared/ipc/modules/worktrees/contract";
import { branchesHandlers } from "./modules/branches/handlers";
import { dialogHandlers } from "./modules/dialog/handlers";
import { fsHandlers } from "./modules/fs/handlers";
import { githubCliHandlers } from "./modules/githubCli/handlers";
import { globalConfigHandlers } from "./modules/globalConfig/handlers";
import { launchersHandlers } from "./modules/launchers/handlers";
import { menuHandlers } from "./modules/menu/handlers";
import { packageScriptsHandlers } from "./modules/packageScripts/handlers";
import { portPoolHandlers } from "./modules/portPool/handlers";
import { projectsHandlers } from "./modules/projects/handlers";
import { runtimeHandlers } from "./modules/runtime/handlers";
import { scriptsHandlers } from "./modules/scripts/handlers";
import { shellHandlers } from "./modules/shell/handlers";
import { shigomoriHandlers } from "./modules/shigomori/handlers";
import { updaterHandlers } from "./modules/updater/handlers";
import { worktreesHandlers } from "./modules/worktrees/handlers";
import { registerContract } from "./register";

export function registerIpcHandlers(): void {
  registerContract(projectsContract, projectsHandlers);
  registerContract(dialogContract, dialogHandlers);
  registerContract(runtimeContract, runtimeHandlers);
  registerContract(shellContract, shellHandlers);
  registerContract(branchesContract, branchesHandlers);
  registerContract(globalConfigContract, globalConfigHandlers);
  registerContract(portPoolContract, portPoolHandlers);
  registerContract(menuContract, menuHandlers);
  registerContract(launchersContract, launchersHandlers);
  registerContract(packageScriptsContract, packageScriptsHandlers);
  registerContract(fsContract, fsHandlers);
  registerContract(githubCliContract, githubCliHandlers);
  registerContract(worktreesContract, worktreesHandlers);
  registerContract(scriptsContract, scriptsHandlers);
  registerContract(shigomoriContract, shigomoriHandlers);
  registerContract(updaterContract, updaterHandlers);
}
