import { dialogContract } from "@shared/ipc/modules/dialog/contract";
import { projectsContract } from "@shared/ipc/modules/projects/contract";
import { runtimeContract } from "@shared/ipc/modules/runtime/contract";
import { shellContract } from "@shared/ipc/modules/shell/contract";
import { dialogHandlers } from "./modules/dialog/handlers";
import { projectsHandlers } from "./modules/projects/handlers";
import { runtimeHandlers } from "./modules/runtime/handlers";
import { shellHandlers } from "./modules/shell/handlers";
import { registerBranchHandlers } from "./branches";
import { registerFsHandlers } from "./fs";
import { registerGithubCliHandlers } from "./githubCli";
import { registerGlobalConfigHandlers } from "./globalConfig";
import { registerLauncherHandlers } from "./launchers";
import { registerMenuHandlers } from "./menu";
import { registerPackageScriptHandlers } from "./packageScripts";
import { registerPortPoolHandlers } from "./portPool";
import { registerContract } from "./register";
import { registerScriptHandlers } from "./scripts";
import { registerShigomoriHandlers } from "./shigomori";
import { registerUpdaterHandlers } from "./updater";
import { registerWorktreeHandlers } from "./worktrees";

export function registerIpcHandlers(): void {
  registerContract(projectsContract, projectsHandlers);
  registerContract(dialogContract, dialogHandlers);
  registerContract(runtimeContract, runtimeHandlers);
  registerContract(shellContract, shellHandlers);
  registerWorktreeHandlers();
  registerBranchHandlers();
  registerLauncherHandlers();
  registerScriptHandlers();
  registerPackageScriptHandlers();
  registerPortPoolHandlers();
  registerGithubCliHandlers();
  registerFsHandlers();
  registerShigomoriHandlers();
  registerGlobalConfigHandlers();
  registerMenuHandlers();
  registerUpdaterHandlers();
}
