// The menu bar icon. Generated by scripts/generate-tray-icon.mjs (run
// `node scripts/generate-tray-icon.mjs --check` to detect drift); see
// that file for why the bytes live in source instead of assets/.
//
// It is a *template* image: alpha-only artwork that AppKit tints to
// match the menu bar, so it stays legible in light menu bars, dark menu
// bars, and while the menu bar item is highlighted. That is also why
// the artwork is monochrome by construction -- a colored status dot
// baked in here would be inverted to nonsense on selection.
import { nativeImage, type NativeImage } from "electron";

const TRAY_ICON_1X =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAgUlEQVR42q3QsQmDUBgE4M9CeDZWGcEmtQtkk6eVpZAxbNzAxhncLxAUfGIsglcd/Pcfd8ddKLwVKw+iURT2gtKsXHk0qA3iL8GoRm382yFoLVcZqEzytMVekOl16TloLJqvaeZl9kgFW6xWpTd7Hmfaii0m3fE7LZafD3067l34AEknGxqQMW82AAAAAElFTkSuQmCC";
const TRAY_ICON_2X =
  "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAABJ0lEQVR42t2VoY7CQBCGv+RCSnIOcVmLpALFY2BJ+gpYgkOgeQ2eAUwlCATpG1wNtgmnDkWZS4dgoDtHC0Gwq7rT/5vuP7NbeMPRouWJBDgcgS3vkZDQu1lvEhGTkhIT0fQDJgjC5EY+46CRYh6Y+RFTfWV6tRqp/ERGxkkRURVAQKzyOSEhc0XEPi/KAI4UISPUp5AMIcW9EPDwFh428QllPDdSorG13Ug+ADRYIOQM7Fb2A9rsEPZ06wJG5AgrPusBOnwjHBla4sKojQI2V0Y5lrq+5cuS+0rVYanV/6Fv5S9rlgZtRvrxwi9jPvzysnZNWLBT64rsY/suKjswl3lkS9/K7gfk7FkxtKyztrBmQPe/utc6cVXLWAFx59Vte3HHz+PNxh96xdSjxucNOgAAAABJRU5ErkJggg==";

export function trayIcon(): NativeImage {
  const image = nativeImage.createFromDataURL(
    `data:image/png;base64,${TRAY_ICON_1X}`,
  );
  image.addRepresentation({
    scaleFactor: 2,
    dataURL: `data:image/png;base64,${TRAY_ICON_2X}`,
  });
  image.setTemplateImage(true);
  return image;
}
